
package org.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ShareMarketServer", targetNamespace = "http://server.org/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface ShareMarketServer {


    /**
     * 
     * @param shareCount
     * @param targetMarket
     * @param shareID
     * @param buyerID
     * @param shareType
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://server.org/ShareMarketServer/purchaseRemoteShareRequest", output = "http://server.org/ShareMarketServer/purchaseRemoteShareResponse")
    public String purchaseRemoteShare(
        @WebParam(name = "buyerID", partName = "buyerID")
        String buyerID,
        @WebParam(name = "shareID", partName = "shareID")
        String shareID,
        @WebParam(name = "shareType", partName = "shareType")
        String shareType,
        @WebParam(name = "shareCount", partName = "shareCount")
        int shareCount,
        @WebParam(name = "targetMarket", partName = "targetMarket")
        String targetMarket);

    /**
     * 
     * @param shareType
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://server.org/ShareMarketServer/listShareAvailabilityRequest", output = "http://server.org/ShareMarketServer/listShareAvailabilityResponse")
    public String listShareAvailability(
        @WebParam(name = "shareType", partName = "shareType")
        String shareType);

    /**
     * 
     * @param buyerID
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://server.org/ShareMarketServer/getSharesRequest", output = "http://server.org/ShareMarketServer/getSharesResponse")
    public String getShares(
        @WebParam(name = "buyerID", partName = "buyerID")
        String buyerID);

    /**
     * 
     * @param shareID
     * @param shareType
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://server.org/ShareMarketServer/removeShareRequest", output = "http://server.org/ShareMarketServer/removeShareResponse")
    public String removeShare(
        @WebParam(name = "shareID", partName = "shareID")
        String shareID,
        @WebParam(name = "shareType", partName = "shareType")
        String shareType);

    /**
     * 
     * @param shareCount
     * @param targetMarket
     * @param shareID
     * @param buyerID
     * @param shareType
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://server.org/ShareMarketServer/sellRemoteShareRequest", output = "http://server.org/ShareMarketServer/sellRemoteShareResponse")
    public String sellRemoteShare(
        @WebParam(name = "buyerID", partName = "buyerID")
        String buyerID,
        @WebParam(name = "shareID", partName = "shareID")
        String shareID,
        @WebParam(name = "shareType", partName = "shareType")
        String shareType,
        @WebParam(name = "shareCount", partName = "shareCount")
        int shareCount,
        @WebParam(name = "targetMarket", partName = "targetMarket")
        String targetMarket);

    /**
     * 
     * @param newShareType
     * @param oldShareID
     * @param newShareID
     * @param oldShareType
     * @param buyerID
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://server.org/ShareMarketServer/swapSharesRequest", output = "http://server.org/ShareMarketServer/swapSharesResponse")
    public String swapShares(
        @WebParam(name = "buyerID", partName = "buyerID")
        String buyerID,
        @WebParam(name = "oldShareID", partName = "oldShareID")
        String oldShareID,
        @WebParam(name = "oldShareType", partName = "oldShareType")
        String oldShareType,
        @WebParam(name = "newShareID", partName = "newShareID")
        String newShareID,
        @WebParam(name = "newShareType", partName = "newShareType")
        String newShareType);

    /**
     * 
     * @param shareCount
     * @param shareID
     * @param buyerID
     * @param shareType
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://server.org/ShareMarketServer/purchaseShareRequest", output = "http://server.org/ShareMarketServer/purchaseShareResponse")
    public String purchaseShare(
        @WebParam(name = "buyerID", partName = "buyerID")
        String buyerID,
        @WebParam(name = "shareID", partName = "shareID")
        String shareID,
        @WebParam(name = "shareType", partName = "shareType")
        String shareType,
        @WebParam(name = "shareCount", partName = "shareCount")
        int shareCount);

    /**
     * 
     * @param shareCount
     * @param shareID
     * @param buyerID
     * @param shareType
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://server.org/ShareMarketServer/sellShareRequest", output = "http://server.org/ShareMarketServer/sellShareResponse")
    public String sellShare(
        @WebParam(name = "buyerID", partName = "buyerID")
        String buyerID,
        @WebParam(name = "shareID", partName = "shareID")
        String shareID,
        @WebParam(name = "shareType", partName = "shareType")
        String shareType,
        @WebParam(name = "shareCount", partName = "shareCount")
        int shareCount);

    /**
     * 
     * @param shareID
     * @param shareType
     * @param capacity
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://server.org/ShareMarketServer/addShareRequest", output = "http://server.org/ShareMarketServer/addShareResponse")
    public String addShare(
        @WebParam(name = "shareID", partName = "shareID")
        String shareID,
        @WebParam(name = "shareType", partName = "shareType")
        String shareType,
        @WebParam(name = "capacity", partName = "capacity")
        int capacity);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @param arg6
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://server.org/ShareMarketServer/handleRemoteSwapRequest", output = "http://server.org/ShareMarketServer/handleRemoteSwapResponse")
    public String handleRemoteSwap(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4,
        @WebParam(name = "arg5", partName = "arg5")
        int arg5,
        @WebParam(name = "arg6", partName = "arg6")
        String arg6);

}
